ServerName: lobby

#注意此开关只需要在一个服打开
#是否开启传送功能
Switch: false

Mysql:
  host: localhost
  port: 3306
  database: getofflineloc
  username: root
  password: ""
Redis:
  host: localhost
  port: 6379
  password: ""
