name: GetOfflineLoc
version: '${project.version}'
main: yumcraft.getofflineloc.GetOfflineLoc
api-version: 1.19
authors: [ AyolK , Doofenshmirtz ]
softdepend: [ServerTeleport]
commands:
  GetOfflineLoc:
    aliases:
      - "GOL"
      - "gol"
